dist: trusty
language: python
python:
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install tinydownload
  - pip install pytest-cov
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get -y install ffmpeg
addons:
  apt:
    packages:
      - automake
      - autoconf
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libfdk-aac-dev
      - libopus-dev
      - pkg-config
      - texinfo
      - zlib1g-dev
      - yasm
      - nasm
      - libmp3lame-dev
      - libav-tools
install:
  - pip install -r requirements.txt
script: python -m pytest
after_success:
  - # pip install codecov
  - # codecov
